# Generated by Django 4.2.20 on 2025-06-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(choices=[('overview', 'Overview'), ('detailed', 'Detailed'), ('compact', 'Compact')], default='overview', max_length=20)),
                ('refresh_interval', models.IntegerField(default=300)),
                ('display_preferences', models.JSONField(default=dict)),
                ('widgets_configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
    ]
