# Generated by Django 4.2.20 on 2025-06-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
        ('ai_predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathertrend',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location'),
        ),
        migrations.AddField(
            model_name='safetyrecommendation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location'),
        ),
        migrations.AddField(
            model_name='extremeevent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location'),
        ),
    ]
